CREATE TABLE students(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(255) NOT NULL,
    last_name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    enrollment_date DATE NOT NULL
    );

COMMENT ON TABLE students IS 'Table to store student information and enrollment data';
COMMENT ON COLUMN students.id IS 'Unique identifier for each student';
COMMENT ON COLUMN students.email IS 'Student email address, must be unique';
